# Generated by Django 4.1.2 on 2022-10-23 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Имя')),
                ('user_status', models.CharField(blank=True, max_length=150, verbose_name='Статус')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('experience', models.CharField(blank=True, choices=[('JR', 'Junior'), ('ML', 'Middle'), ('SR', 'Senior')], default='JR', max_length=2, verbose_name='Опыт')),
                ('sex', models.CharField(blank=True, choices=[('ML', 'Male'), ('FL', 'Female')], max_length=2, null=True, verbose_name='Гендер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователей',
            },
        ),
    ]
