# Generated by Django 4.1.2 on 2022-12-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='user',
            new_name='recipient',
        ),
    ]
