# Generated by Django 4.1.2 on 2023-04-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_friendrequest_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreadedmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='сообщение'),
        ),
    ]
