# Generated by Django 4.1.2 on 2023-04-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userreadedmessage_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluserdata',
            old_name='user_status',
            new_name='status',
        ),
    ]
